// Code generated by scripts/generate_go_funcs; DO NOT EDIT.
package jsoncfg

func (c *JSONCfg) Get(key ...interface{}) interface{} {
	return c.config.Get(key...)
}

func (c *JSONCfg) GetArray(key ...interface{}) []interface{} {
	return c.config.GetArray(key...)
}

func (c *JSONCfg) GetMap(key ...interface{}) map[string]interface{} {
	return c.config.GetMap(key...)
}

func (c *JSONCfg) GetDiff(key ...interface{}) interface{} {
	return c.diff.Get(key...)
}

func (c *JSONCfg) GetDiffArray(key ...interface{}) []interface{} {
	return c.diff.GetArray(key...)
}

func (c *JSONCfg) GetDiffMap(key ...interface{}) map[string]interface{} {
	return c.diff.GetMap(key...)
}

func (c *JSONCfg) GetBool(key ...interface{}) bool {
	return c.config.GetBool(key...)
}

func (c *JSONCfg) GetBoolArray(key ...interface{}) []bool {
	return c.config.GetBoolArray(key...)
}

func (c *JSONCfg) GetBoolMap(key ...interface{}) map[string]bool {
	return c.config.GetBoolMap(key...)
}

func (c *JSONCfg) GetDiffBool(key ...interface{}) bool {
	return c.diff.GetBool(key...)
}

func (c *JSONCfg) GetDiffBoolArray(key ...interface{}) []bool {
	return c.diff.GetBoolArray(key...)
}

func (c *JSONCfg) GetDiffBoolMap(key ...interface{}) map[string]bool {
	return c.diff.GetBoolMap(key...)
}

func (c *JSONCfg) GetFloat32(key ...interface{}) float32 {
	return c.config.GetFloat32(key...)
}

func (c *JSONCfg) GetFloat32Array(key ...interface{}) []float32 {
	return c.config.GetFloat32Array(key...)
}

func (c *JSONCfg) GetFloat32Map(key ...interface{}) map[string]float32 {
	return c.config.GetFloat32Map(key...)
}

func (c *JSONCfg) GetDiffFloat32(key ...interface{}) float32 {
	return c.diff.GetFloat32(key...)
}

func (c *JSONCfg) GetDiffFloat32Array(key ...interface{}) []float32 {
	return c.diff.GetFloat32Array(key...)
}

func (c *JSONCfg) GetDiffFloat32Map(key ...interface{}) map[string]float32 {
	return c.diff.GetFloat32Map(key...)
}

func (c *JSONCfg) GetFloat64(key ...interface{}) float64 {
	return c.config.GetFloat64(key...)
}

func (c *JSONCfg) GetFloat64Array(key ...interface{}) []float64 {
	return c.config.GetFloat64Array(key...)
}

func (c *JSONCfg) GetFloat64Map(key ...interface{}) map[string]float64 {
	return c.config.GetFloat64Map(key...)
}

func (c *JSONCfg) GetDiffFloat64(key ...interface{}) float64 {
	return c.diff.GetFloat64(key...)
}

func (c *JSONCfg) GetDiffFloat64Array(key ...interface{}) []float64 {
	return c.diff.GetFloat64Array(key...)
}

func (c *JSONCfg) GetDiffFloat64Map(key ...interface{}) map[string]float64 {
	return c.diff.GetFloat64Map(key...)
}

func (c *JSONCfg) GetInt(key ...interface{}) int {
	return c.config.GetInt(key...)
}

func (c *JSONCfg) GetIntArray(key ...interface{}) []int {
	return c.config.GetIntArray(key...)
}

func (c *JSONCfg) GetIntMap(key ...interface{}) map[string]int {
	return c.config.GetIntMap(key...)
}

func (c *JSONCfg) GetDiffInt(key ...interface{}) int {
	return c.diff.GetInt(key...)
}

func (c *JSONCfg) GetDiffIntArray(key ...interface{}) []int {
	return c.diff.GetIntArray(key...)
}

func (c *JSONCfg) GetDiffIntMap(key ...interface{}) map[string]int {
	return c.diff.GetIntMap(key...)
}

func (c *JSONCfg) GetInt16(key ...interface{}) int16 {
	return c.config.GetInt16(key...)
}

func (c *JSONCfg) GetInt16Array(key ...interface{}) []int16 {
	return c.config.GetInt16Array(key...)
}

func (c *JSONCfg) GetInt16Map(key ...interface{}) map[string]int16 {
	return c.config.GetInt16Map(key...)
}

func (c *JSONCfg) GetDiffInt16(key ...interface{}) int16 {
	return c.diff.GetInt16(key...)
}

func (c *JSONCfg) GetDiffInt16Array(key ...interface{}) []int16 {
	return c.diff.GetInt16Array(key...)
}

func (c *JSONCfg) GetDiffInt16Map(key ...interface{}) map[string]int16 {
	return c.diff.GetInt16Map(key...)
}

func (c *JSONCfg) GetInt32(key ...interface{}) int32 {
	return c.config.GetInt32(key...)
}

func (c *JSONCfg) GetInt32Array(key ...interface{}) []int32 {
	return c.config.GetInt32Array(key...)
}

func (c *JSONCfg) GetInt32Map(key ...interface{}) map[string]int32 {
	return c.config.GetInt32Map(key...)
}

func (c *JSONCfg) GetDiffInt32(key ...interface{}) int32 {
	return c.diff.GetInt32(key...)
}

func (c *JSONCfg) GetDiffInt32Array(key ...interface{}) []int32 {
	return c.diff.GetInt32Array(key...)
}

func (c *JSONCfg) GetDiffInt32Map(key ...interface{}) map[string]int32 {
	return c.diff.GetInt32Map(key...)
}

func (c *JSONCfg) GetInt64(key ...interface{}) int64 {
	return c.config.GetInt64(key...)
}

func (c *JSONCfg) GetInt64Array(key ...interface{}) []int64 {
	return c.config.GetInt64Array(key...)
}

func (c *JSONCfg) GetInt64Map(key ...interface{}) map[string]int64 {
	return c.config.GetInt64Map(key...)
}

func (c *JSONCfg) GetDiffInt64(key ...interface{}) int64 {
	return c.diff.GetInt64(key...)
}

func (c *JSONCfg) GetDiffInt64Array(key ...interface{}) []int64 {
	return c.diff.GetInt64Array(key...)
}

func (c *JSONCfg) GetDiffInt64Map(key ...interface{}) map[string]int64 {
	return c.diff.GetInt64Map(key...)
}

func (c *JSONCfg) GetString(key ...interface{}) string {
	return c.config.GetString(key...)
}

func (c *JSONCfg) GetStringArray(key ...interface{}) []string {
	return c.config.GetStringArray(key...)
}

func (c *JSONCfg) GetStringMap(key ...interface{}) map[string]string {
	return c.config.GetStringMap(key...)
}

func (c *JSONCfg) GetDiffString(key ...interface{}) string {
	return c.diff.GetString(key...)
}

func (c *JSONCfg) GetDiffStringArray(key ...interface{}) []string {
	return c.diff.GetStringArray(key...)
}

func (c *JSONCfg) GetDiffStringMap(key ...interface{}) map[string]string {
	return c.diff.GetStringMap(key...)
}

func (c *JSONCfg) GetUint(key ...interface{}) uint {
	return c.config.GetUint(key...)
}

func (c *JSONCfg) GetUintArray(key ...interface{}) []uint {
	return c.config.GetUintArray(key...)
}

func (c *JSONCfg) GetUintMap(key ...interface{}) map[string]uint {
	return c.config.GetUintMap(key...)
}

func (c *JSONCfg) GetDiffUint(key ...interface{}) uint {
	return c.diff.GetUint(key...)
}

func (c *JSONCfg) GetDiffUintArray(key ...interface{}) []uint {
	return c.diff.GetUintArray(key...)
}

func (c *JSONCfg) GetDiffUintMap(key ...interface{}) map[string]uint {
	return c.diff.GetUintMap(key...)
}

func (c *JSONCfg) GetUint16(key ...interface{}) uint16 {
	return c.config.GetUint16(key...)
}

func (c *JSONCfg) GetUint16Array(key ...interface{}) []uint16 {
	return c.config.GetUint16Array(key...)
}

func (c *JSONCfg) GetUint16Map(key ...interface{}) map[string]uint16 {
	return c.config.GetUint16Map(key...)
}

func (c *JSONCfg) GetDiffUint16(key ...interface{}) uint16 {
	return c.diff.GetUint16(key...)
}

func (c *JSONCfg) GetDiffUint16Array(key ...interface{}) []uint16 {
	return c.diff.GetUint16Array(key...)
}

func (c *JSONCfg) GetDiffUint16Map(key ...interface{}) map[string]uint16 {
	return c.diff.GetUint16Map(key...)
}

func (c *JSONCfg) GetUint32(key ...interface{}) uint32 {
	return c.config.GetUint32(key...)
}

func (c *JSONCfg) GetUint32Array(key ...interface{}) []uint32 {
	return c.config.GetUint32Array(key...)
}

func (c *JSONCfg) GetUint32Map(key ...interface{}) map[string]uint32 {
	return c.config.GetUint32Map(key...)
}

func (c *JSONCfg) GetDiffUint32(key ...interface{}) uint32 {
	return c.diff.GetUint32(key...)
}

func (c *JSONCfg) GetDiffUint32Array(key ...interface{}) []uint32 {
	return c.diff.GetUint32Array(key...)
}

func (c *JSONCfg) GetDiffUint32Map(key ...interface{}) map[string]uint32 {
	return c.diff.GetUint32Map(key...)
}

func (c *JSONCfg) GetUint64(key ...interface{}) uint64 {
	return c.config.GetUint64(key...)
}

func (c *JSONCfg) GetUint64Array(key ...interface{}) []uint64 {
	return c.config.GetUint64Array(key...)
}

func (c *JSONCfg) GetUint64Map(key ...interface{}) map[string]uint64 {
	return c.config.GetUint64Map(key...)
}

func (c *JSONCfg) GetDiffUint64(key ...interface{}) uint64 {
	return c.diff.GetUint64(key...)
}

func (c *JSONCfg) GetDiffUint64Array(key ...interface{}) []uint64 {
	return c.diff.GetUint64Array(key...)
}

func (c *JSONCfg) GetDiffUint64Map(key ...interface{}) map[string]uint64 {
	return c.diff.GetUint64Map(key...)
}
